module.exports = {
    ARIES_DOWNLOAD_VIDEO_QUENE: 'ARIES_DOWNLOAD_VIDEO_QUENE',
    ARIES_DOWNLOAD_PICTURE_QUENE: 'ARIES_DOWNLOAD_PICTURE_QUENE',
    ARIES_DOWNLOAD_AUDIO_QUENE: 'ARIES_DOWNLOAD_AUDIO_QUENE',
    ARIES_DOWNLOAD_FILE_QUENE: 'ARIES_DOWNLOAD_FILE_QUENE',
}