module.exports = {
    ARIES_DOWNLOAD_VIDEO_QUEUE: 'ARIES_DOWNLOAD_VIDEO_QUEUE',
    ARIES_DOWNLOAD_PICTURE_QUEUE: 'ARIES_DOWNLOAD_PICTURE_QUEUE',
    ARIES_DOWNLOAD_AUDIO_QUEUE: 'ARIES_DOWNLOAD_AUDIO_QUEUE',
    ARIES_DOWNLOAD_FILE_QUEUE: 'ARIES_DOWNLOAD_FILE_QUEUE',
}