module.exports = {
    AXIES_DOWNLOAD_VIDEO_QUENE: 'AXIES_DOWNLOAD_VIDEO_QUENE',
    AXIES_DOWNLOAD_PICTURE_QUENE: 'AXIES_DOWNLOAD_PICTURE_QUENE',
    AXIES_DOWNLOAD_AUDIO_QUENE: 'AXIES_DOWNLOAD_AUDIO_QUENE',
    AXIES_DOWNLOAD_FILE_QUENE: 'AXIES_DOWNLOAD_FILE_QUENE',
}